# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

uppertri_pcm <- function(zsamples, n, nsamples) {
    .Call('_graphppm_uppertri_pcm', PACKAGE = 'graphppm', zsamples, n, nsamples)
}

update_uppertri_pcm <- function(uppertri_pcm, z, n) {
    invisible(.Call('_graphppm_update_uppertri_pcm', PACKAGE = 'graphppm', uppertri_pcm, z, n))
}

update_uppertri_logpsm <- function(uppertri_logpsm, z, n, logweight) {
    invisible(.Call('_graphppm_update_uppertri_logpsm', PACKAGE = 'graphppm', uppertri_logpsm, z, n, logweight))
}

runcppWilson <- function(n, graph_edge_list, rootvertex, ordering, maxwalk) {
    .Call('_graphppm_runcppWilson', PACKAGE = 'graphppm', n, graph_edge_list, rootvertex, ordering, maxwalk)
}

