# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.runcppWilson <- function(n, graph_edge_list, rootvertex, ordering, maxwalk) {
    .Call(`_graphppm_runcppWilson`, n, graph_edge_list, rootvertex, ordering, maxwalk)
}

